# See https://stylelint.io/user-guide/rules/list
# Also https://github.com/kristerkari/stylelint-scss#list-of-rules

extends:
  - stylelint-config-standard-scss
  - stylelint-prettier/recommended
plugins:
  - stylelint-prettier

ignoreFiles:
  - '**/*.js'
  - '**/*.jsx'
  - '**/*.ts'
  - '**/*.tsx'

rules:
  prettier/prettier: true

  # possible errors (these are all on by default)
  no-descending-specificity: null

  # limit language features
  color-named: always-where-possible
  declaration-no-important: true
  function-url-no-scheme-relative: true
  selector-class-pattern: null
