parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - simple-import-sort
extends:
  - plugin:storybook/recommended
rules:
  # Import
  simple-import-sort/imports: 1
  import/order: 0
